package Data;


/**
* Data/DataList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataList.idl
* mercoledì 24 marzo 2010 19.38.16 CET
*/

public interface DataList extends DataListOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DataList
