package Data;


/**
* Data/DataListPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataList.idl
* mercoledì 24 marzo 2010 19.38.16 CET
*/

public abstract class DataListPOA extends org.omg.PortableServer.Servant
 implements Data.DataListOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertData", new java.lang.Integer (0));
    _methods.put ("returnList", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Data/DataList/insertData
       {
         org.omg.CORBA.Any a = in.read_any ();
         this.insertData (a);
         out = $rh.createReply();
         break;
       }

       case 1:  // Data/DataList/returnList
       {
         org.omg.CORBA.Any $result[] = null;
         $result = this.returnList ();
         out = $rh.createReply();
         Data.dListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Data/DataList:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DataList _this() 
  {
    return DataListHelper.narrow(
    super._this_object());
  }

  public DataList _this(org.omg.CORBA.ORB orb) 
  {
    return DataListHelper.narrow(
    super._this_object(orb));
  }


} // class DataListPOA
