package Data;


/**
* Data/DataListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataList.idl
* mercoledì 24 marzo 2010 19.38.16 CET
*/

abstract public class DataListHelper
{
  private static String  _id = "IDL:Data/DataList:1.0";

  public static void insert (org.omg.CORBA.Any a, Data.DataList that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Data.DataList extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Data.DataListHelper.id (), "DataList");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Data.DataList read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DataListStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Data.DataList value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Data.DataList narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Data.DataList)
      return (Data.DataList)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Data._DataListStub stub = new Data._DataListStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Data.DataList unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Data.DataList)
      return (Data.DataList)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Data._DataListStub stub = new Data._DataListStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
