package Data;

/**
* Data/DataListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataList.idl
* mercoledì 24 marzo 2010 19.38.16 CET
*/

public final class DataListHolder implements org.omg.CORBA.portable.Streamable
{
  public Data.DataList value = null;

  public DataListHolder ()
  {
  }

  public DataListHolder (Data.DataList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Data.DataListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Data.DataListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Data.DataListHelper.type ();
  }

}
