package Data;


/**
* Data/DataListOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataList.idl
* mercoledì 24 marzo 2010 19.38.16 CET
*/

public interface DataListOperations 
{
  void insertData (org.omg.CORBA.Any a);
  org.omg.CORBA.Any[] returnList ();
} // interface DataListOperations
