package Data;


/**
* Data/dListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataList.idl
* mercoledì 24 marzo 2010 19.38.16 CET
*/

public final class dListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.Any value[] = null;

  public dListHolder ()
  {
  }

  public dListHolder (org.omg.CORBA.Any[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Data.dListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Data.dListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Data.dListHelper.type ();
  }

}
