package CosEventComm;

/**
* CosEventComm/DisconnectedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* martedì 16 marzo 2010 10.44.20 CET
*/

public final class DisconnectedHolder implements org.omg.CORBA.portable.Streamable
{
  public CosEventComm.Disconnected value = null;

  public DisconnectedHolder ()
  {
  }

  public DisconnectedHolder (CosEventComm.Disconnected initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosEventComm.DisconnectedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosEventComm.DisconnectedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosEventComm.DisconnectedHelper.type ();
  }

}
