package CosEventComm;


/**
* CosEventComm/PullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* martedì 16 marzo 2010 10.44.20 CET
*/

public interface PullConsumer extends PullConsumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PullConsumer
