package CosEventComm;


/**
* CosEventComm/PullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* martedì 16 marzo 2010 10.44.20 CET
*/

public interface PullConsumerOperations 
{
  void disconnect_pull_consumer ();
} // interface PullConsumerOperations
