package CosEventComm;


/**
* CosEventComm/PullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* martedì 16 marzo 2010 10.44.20 CET
*/

public interface PullSupplierOperations 
{
  org.omg.CORBA.Any pull () throws CosEventComm.Disconnected;
  org.omg.CORBA.Any try_pull (org.omg.CORBA.BooleanHolder has_event) throws CosEventComm.Disconnected;
  void disconnect_pull_supplier ();
} // interface PullSupplierOperations
