package CosEventComm;


/**
* CosEventComm/PushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventComm.idl
* martedì 16 marzo 2010 10.44.20 CET
*/

public interface PushConsumerOperations 
{
  void push (org.omg.CORBA.Any data) throws CosEventComm.Disconnected;
  void disconnect_push_consumer ();
} // interface PushConsumerOperations
