package it.yellow.fe.controller;

import java.util.HashMap;

public class CountryUtils {

	//che cosa bruttissima, per non dover usare un db
	public static HashMap<String, String> coutryCodes = new HashMap<String, String>(){{
		put("Andorra","AD");
		put("United Arab Emirates","AE");
		put("Afghanistan","AF");
		put("Antigua and Barbuda","AG");
		put("Anguilla","AI");
		put("Albania","AL");
		put("Armenia","AM");
		put("Angola","AO");
		put("Antarctica","AQ");
		put("Argentina","AR");
		put("American Samoa","AS");
		put("Austria","AT");
		put("Australia","AU");
		put("Aruba","AW");
		put("Åland Islands","AX");
		put("Azerbaijan","AZ");
		put("Bosnia and Herzegovina","BA");
		put("Barbados","BB");
		put("Bangladesh","BD");
		put("Belgium","BE");
		put("Burkina Faso","BF");
		put("Bulgaria","BG");
		put("Bahrain","BH");
		put("Burundi","BI");
		put("Benin","BJ");
		put("Saint Barthélemy","BL");
		put("Bermuda","BM");
		put("Brunei Darussalam","BN");
		put("Bolivia, Plurinational State of","BO");
		put("Bonaire, Sint Eustatius and Saba","BQ");
		put("Brazil","BR");
		put("Bahamas","BS");
		put("Bhutan","BT");
		put("Bouvet Island","BV");
		put("Botswana","BW");
		put("Belarus","BY");
		put("Belize","BZ");
		put("Canada","CA");
		put("Cocos (Keeling) Islands","CC");
		put("Congo, the Democratic Republic of the","CD");
		put("Central African Republic","CF");
		put("Congo","CG");
		put("Switzerland","CH");
		put("Côte d'Ivoire","CI");
		put("Cook Islands","CK");
		put("Chile","CL");
		put("Cameroon","CM");
		put("China","CN");
		put("Colombia","CO");
		put("Costa Rica","CR");
		put("Cuba","CU");
		put("Cape Verde","CV");
		put("Curaçao","CW");
		put("Christmas Island","CX");
		put("Cyprus","CY");
		put("Czech Republic","CZ");
		put("Germany","DE");
		put("Djibouti","DJ");
		put("Denmark","DK");
		put("Dominica","DM");
		put("Dominican Republic","DO");
		put("Algeria","DZ");
		put("Ecuador","EC");
		put("Estonia","EE");
		put("Egypt","EG");
		put("Western Sahara","EH");
		put("Eritrea","ER");
		put("Spain","ES");
		put("Ethiopia","ET");
		put("Finland","FI");
		put("Fiji","FJ");
		put("Falkland Islands (Malvinas)","FK");
		put("Micronesia, Federated States of","FM");
		put("Faroe Islands","FO");
		put("France","FR");
		put("Gabon","GA");
		put("United Kingdom","GB");
		put("Grenada","GD");
		put("Georgia","GE");
		put("French Guiana","GF");
		put("Guernsey","GG");
		put("Ghana","GH");
		put("Gibraltar","GI");
		put("Greenland","GL");
		put("Gambia","GM");
		put("Guinea","GN");
		put("Guadeloupe","GP");
		put("Equatorial Guinea","GQ");
		put("Greece","GR");
		put("South Georgia and the South Sandwich Islands","GS");
		put("Guatemala","GT");
		put("Guam","GU");
		put("Guinea-Bissau","GW");
		put("Guyana","GY");
		put("Hong Kong","HK");
		put("Heard Island and McDonald Islands","HM");
		put("Honduras","HN");
		put("Croatia","HR");
		put("Haiti","HT");
		put("Hungary","HU");
		put("Indonesia","ID");
		put("Ireland","IE");
		put("Israel","IL");
		put("Isle of Man","IM");
		put("India","IN");
		put("British Indian Ocean Territory","IO");
		put("Iraq","IQ");
		put("Iran, Islamic Republic of","IR");
		put("Iceland","IS");
		put("Italy","IT");
		put("Jersey","JE");
		put("Jamaica","JM");
		put("Jordan","JO");
		put("Japan","JP");
		put("Kenya","KE");
		put("Kyrgyzstan","KG");
		put("Cambodia","KH");
		put("Kiribati","KI");
		put("Comoros","KM");
		put("Saint Kitts and Nevis","KN");
		put("Korea, Democratic People's Republic of","KP");
		put("Korea, Republic of","KR");
		put("Kuwait","KW");
		put("Cayman Islands","KY");
		put("Kazakhstan","KZ");
		put("Lao People's Democratic Republic","LA");
		put("Lebanon","LB");
		put("Saint Lucia","LC");
		put("Liechtenstein","LI");
		put("Sri Lanka","LK");
		put("Liberia","LR");
		put("Lesotho","LS");
		put("Lithuania","LT");
		put("Luxembourg","LU");
		put("Latvia","LV");
		put("Libya","LY");
		put("Morocco","MA");
		put("Monaco","MC");
		put("Moldova, Republic of","MD");
		put("Montenegro","ME");
		put("Saint Martin (French part)","MF");
		put("Madagascar","MG");
		put("Marshall Islands","MH");
		put("Macedonia, the former Yugoslav Republic of","MK");
		put("Mali","ML");
		put("Myanmar","MM");
		put("Mongolia","MN");
		put("Macao","MO");
		put("Northern Mariana Islands","MP");
		put("Martinique","MQ");
		put("Mauritania","MR");
		put("Montserrat","MS");
		put("Malta","MT");
		put("Mauritius","MU");
		put("Maldives","MV");
		put("Malawi","MW");
		put("Mexico","MX");
		put("Malaysia","MY");
		put("Mozambique","MZ");
		put("Namibia","NA");
		put("New Caledonia","NC");
		put("Niger","NE");
		put("Norfolk Island","NF");
		put("Nigeria","NG");
		put("Nicaragua","NI");
		put("Netherlands","NL");
		put("Norway","NO");
		put("Nepal","NP");
		put("Nauru","NR");
		put("Niue","NU");
		put("New Zealand","NZ");
		put("Oman","OM");
		put("Panama","PA");
		put("Peru","PE");
		put("French Polynesia","PF");
		put("Papua New Guinea","PG");
		put("Philippines","PH");
		put("Pakistan","PK");
		put("Poland","PL");
		put("Saint Pierre and Miquelon","PM");
		put("Pitcairn","PN");
		put("Puerto Rico","PR");
		put("Palestinian Territory, Occupied","PS");
		put("Portugal","PT");
		put("Palau","PW");
		put("Paraguay","PY");
		put("Qatar","QA");
		put("Réunion","RE");
		put("Romania","RO");
		put("Serbia","RS");
		put("Russian Federation","RU");
		put("Rwanda","RW");
		put("Saudi Arabia","SA");
		put("Solomon Islands","SB");
		put("Seychelles","SC");
		put("Sudan","SD");
		put("Sweden","SE");
		put("Singapore","SG");
		put("Saint Helena, Ascension and Tristan da Cunha","SH");
		put("Slovenia","SI");
		put("Svalbard and Jan Mayen","SJ");
		put("Slovakia","SK");
		put("Sierra Leone","SL");
		put("San Marino","SM");
		put("Senegal","SN");
		put("Somalia","SO");
		put("Suriname","SR");
		put("South Sudan","SS");
		put("Sao Tome and Principe","ST");
		put("El Salvador","SV");
		put("Sint Maarten (Dutch part)","SX");
		put("Syrian Arab Republic","SY");
		put("Swaziland","SZ");
		put("Turks and Caicos Islands","TC");
		put("Chad","TD");
		put("French Southern Territories","TF");
		put("Togo","TG");
		put("Thailand","TH");
		put("Tajikistan","TJ");
		put("Tokelau","TK");
		put("Timor-Leste","TL");
		put("Turkmenistan","TM");
		put("Tunisia","TN");
		put("Tonga","TO");
		put("Turkey","TR");
		put("Trinidad and Tobago","TT");
		put("Tuvalu","TV");
		put("Taiwan, Province of China","TW");
		put("Tanzania, United Republic of","TZ");
		put("Ukraine","UA");
		put("Uganda","UG");
		put("United States Minor Outlying Islands","UM");
		put("United States","US");
		put("Uruguay","UY");
		put("Uzbekistan","UZ");
		put("Holy See (Vatican City State)","VA");
		put("Saint Vincent and the Grenadines","VC");
		put("Venezuela, Bolivarian Republic of","VE");
		put("Virgin Islands, British","VG");
		put("Virgin Islands, U.S.","VI");
		put("Viet Nam","VN");
		put("Vanuatu","VU");
		put("Wallis and Futuna","WF");
		put("Samoa","WS");
		put("Yemen","YE");
		put("Mayotte","YT");
		put("South Africa","ZA");
		put("Zambia","ZM");
		put("Zimbabwe","ZW");
	}};
	
}
