package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/ConsumerAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventChannelAdmin.idl
* martedì 16 marzo 2010 11.29.55 CET
*/

public interface ConsumerAdminOperations 
{
  CosEventChannelAdmin.ProxyPushSupplier obtain_push_supplier ();
  CosEventChannelAdmin.ProxyPullSupplier obtain_pull_supplier ();
} // interface ConsumerAdminOperations
