package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/ProxyPullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventChannelAdmin.idl
* martedì 16 marzo 2010 11.29.55 CET
*/

public interface ProxyPullSupplier extends ProxyPullSupplierOperations, CosEventComm.PullSupplier, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProxyPullSupplier
