package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/SupplierAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEventChannelAdmin.idl
* martedì 16 marzo 2010 11.29.55 CET
*/

public interface SupplierAdminOperations 
{
  CosEventChannelAdmin.ProxyPushConsumer obtain_push_consumer ();
  CosEventChannelAdmin.ProxyPullConsumer obtain_pull_consumer ();
} // interface SupplierAdminOperations
