package it.crevu.db;

// Generated 2-mag-2013 23.42.17 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "crevu")
public class Address implements java.io.Serializable {

	private Integer id;
	private int idUser;
	private String street;
	private String city;
	private String country;
	private String state;
	private String zipCode;
	private String phoneNumber;
	private String cellNumber;
	private String addressEmail;
	private boolean deliveryAddress;
	private boolean predefDeliveryAddress;
	private Date dateCreate;
	private Date dateChange;

	public Address() {
	}

	public Address(int idUser, String street, String city, String country,
			String zipCode, boolean deliveryAddress,
			boolean predefDeliveryAddress) {
		this.idUser = idUser;
		this.street = street;
		this.city = city;
		this.country = country;
		this.zipCode = zipCode;
		this.deliveryAddress = deliveryAddress;
		this.predefDeliveryAddress = predefDeliveryAddress;
	}

	public Address(int idUser, String street, String city, String country,
			String state, String zipCode, String phoneNumber,
			String cellNumber, String addressEmail, boolean deliveryAddress,
			boolean predefDeliveryAddress, Date dateCreate, Date dateChange) {
		this.idUser = idUser;
		this.street = street;
		this.city = city;
		this.country = country;
		this.state = state;
		this.zipCode = zipCode;
		this.phoneNumber = phoneNumber;
		this.cellNumber = cellNumber;
		this.addressEmail = addressEmail;
		this.deliveryAddress = deliveryAddress;
		this.predefDeliveryAddress = predefDeliveryAddress;
		this.dateCreate = dateCreate;
		this.dateChange = dateChange;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "street", nullable = false, length = 200)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "city", nullable = false, length = 200)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", nullable = false, length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip_code", nullable = false, length = 100)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "phone_number", length = 100)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "cell_number", length = 100)
	public String getCellNumber() {
		return this.cellNumber;
	}

	public void setCellNumber(String cellNumber) {
		this.cellNumber = cellNumber;
	}

	@Column(name = "address_email", length = 100)
	public String getAddressEmail() {
		return this.addressEmail;
	}

	public void setAddressEmail(String addressEmail) {
		this.addressEmail = addressEmail;
	}

	@Column(name = "delivery_address", nullable = false)
	public boolean isDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(boolean deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	@Column(name = "predef_delivery_address", nullable = false)
	public boolean isPredefDeliveryAddress() {
		return this.predefDeliveryAddress;
	}

	public void setPredefDeliveryAddress(boolean predefDeliveryAddress) {
		this.predefDeliveryAddress = predefDeliveryAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_change", length = 10)
	public Date getDateChange() {
		return this.dateChange;
	}

	public void setDateChange(Date dateChange) {
		this.dateChange = dateChange;
	}

}
