package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "crevu")
public class Notification implements java.io.Serializable {

	private NotificationId id;
	private int idUser;
	private String text;
	private boolean delivered;

	public Notification() {
	}

	public Notification(NotificationId id, int idUser, String text,
			boolean delivered) {
		this.id = id;
		this.idUser = idUser;
		this.text = text;
		this.delivered = delivered;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", nullable = false, length = 10)) })
	public NotificationId getId() {
		return this.id;
	}

	public void setId(NotificationId id) {
		this.id = id;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "text", nullable = false, length = 100)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "delivered", nullable = false)
	public boolean isDelivered() {
		return this.delivered;
	}

	public void setDelivered(boolean delivered) {
		this.delivered = delivered;
	}

}
