package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrderedTshirt generated by hbm2java
 */
@Entity
@Table(name = "ordered_tshirt", catalog = "crevu")
public class OrderedTshirt implements java.io.Serializable {

	private OrderedTshirtId id;

	public OrderedTshirt() {
	}

	public OrderedTshirt(OrderedTshirtId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idOrderDeal", column = @Column(name = "id_order_deal", nullable = false)),
			@AttributeOverride(name = "idSoldTshirt", column = @Column(name = "id_sold_tshirt", nullable = false)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)) })
	public OrderedTshirtId getId() {
		return this.id;
	}

	public void setId(OrderedTshirtId id) {
		this.id = id;
	}

}
