package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrderDeal generated by hbm2java
 */
@Entity
@Table(name = "order_deal", catalog = "crevu", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id", "date_create" }))
public class OrderDeal implements java.io.Serializable {

	private OrderDealId id;

	public OrderDeal() {
	}

	public OrderDeal(OrderDealId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "orderStatus", column = @Column(name = "order_status", nullable = false, length = 1)),
			@AttributeOverride(name = "idSupplierOrder", column = @Column(name = "id_supplier_order")),
			@AttributeOverride(name = "dispatchReference", column = @Column(name = "dispatch_reference", length = 100)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 1)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)),
			@AttributeOverride(name = "dateChange", column = @Column(name = "date_change", length = 10)) })
	public OrderDealId getId() {
		return this.id;
	}

	public void setId(OrderDealId id) {
		this.id = id;
	}

}
