package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDealId generated by hbm2java
 */
@Embeddable
public class OrderDealId implements java.io.Serializable {

	private int id;
	private char orderStatus;
	private Integer idSupplierOrder;
	private String dispatchReference;
	private char status;
	private Date dateCreate;
	private Date dateChange;

	public OrderDealId() {
	}

	public OrderDealId(int id, char orderStatus, char status) {
		this.id = id;
		this.orderStatus = orderStatus;
		this.status = status;
	}

	public OrderDealId(int id, char orderStatus, Integer idSupplierOrder,
			String dispatchReference, char status, Date dateCreate,
			Date dateChange) {
		this.id = id;
		this.orderStatus = orderStatus;
		this.idSupplierOrder = idSupplierOrder;
		this.dispatchReference = dispatchReference;
		this.status = status;
		this.dateCreate = dateCreate;
		this.dateChange = dateChange;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "order_status", nullable = false, length = 1)
	public char getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(char orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "id_supplier_order")
	public Integer getIdSupplierOrder() {
		return this.idSupplierOrder;
	}

	public void setIdSupplierOrder(Integer idSupplierOrder) {
		this.idSupplierOrder = idSupplierOrder;
	}

	@Column(name = "dispatch_reference", length = 100)
	public String getDispatchReference() {
		return this.dispatchReference;
	}

	public void setDispatchReference(String dispatchReference) {
		this.dispatchReference = dispatchReference;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "date_change", length = 10)
	public Date getDateChange() {
		return this.dateChange;
	}

	public void setDateChange(Date dateChange) {
		this.dateChange = dateChange;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDealId))
			return false;
		OrderDealId castOther = (OrderDealId) other;

		return (this.getId() == castOther.getId())
				&& (this.getOrderStatus() == castOther.getOrderStatus())
				&& ((this.getIdSupplierOrder() == castOther
						.getIdSupplierOrder()) || (this.getIdSupplierOrder() != null
						&& castOther.getIdSupplierOrder() != null && this
						.getIdSupplierOrder().equals(
								castOther.getIdSupplierOrder())))
				&& ((this.getDispatchReference() == castOther
						.getDispatchReference()) || (this
						.getDispatchReference() != null
						&& castOther.getDispatchReference() != null && this
						.getDispatchReference().equals(
								castOther.getDispatchReference())))
				&& (this.getStatus() == castOther.getStatus())
				&& ((this.getDateCreate() == castOther.getDateCreate()) || (this
						.getDateCreate() != null
						&& castOther.getDateCreate() != null && this
						.getDateCreate().equals(castOther.getDateCreate())))
				&& ((this.getDateChange() == castOther.getDateChange()) || (this
						.getDateChange() != null
						&& castOther.getDateChange() != null && this
						.getDateChange().equals(castOther.getDateChange())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getOrderStatus();
		result = 37
				* result
				+ (getIdSupplierOrder() == null ? 0 : this.getIdSupplierOrder()
						.hashCode());
		result = 37
				* result
				+ (getDispatchReference() == null ? 0 : this
						.getDispatchReference().hashCode());
		result = 37 * result + this.getStatus();
		result = 37
				* result
				+ (getDateCreate() == null ? 0 : this.getDateCreate()
						.hashCode());
		result = 37
				* result
				+ (getDateChange() == null ? 0 : this.getDateChange()
						.hashCode());
		return result;
	}

}
