package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentData generated by hbm2java
 */
@Entity
@Table(name = "payment_data", catalog = "crevu")
public class PaymentData implements java.io.Serializable {

	private int idUser;
	private String paymentType;
	private String paymentEmail;
	private String paymentPassword;
	private String creditCardNumber;
	private String creditCardType;
	private String cvv2;
	private Date expriry;
	private Date dateCreate;
	private Date dateChange;

	public PaymentData() {
	}

	public PaymentData(int idUser, String paymentType) {
		this.idUser = idUser;
		this.paymentType = paymentType;
	}

	public PaymentData(int idUser, String paymentType, String paymentEmail,
			String paymentPassword, String creditCardNumber,
			String creditCardType, String cvv2, Date expriry, Date dateCreate,
			Date dateChange) {
		this.idUser = idUser;
		this.paymentType = paymentType;
		this.paymentEmail = paymentEmail;
		this.paymentPassword = paymentPassword;
		this.creditCardNumber = creditCardNumber;
		this.creditCardType = creditCardType;
		this.cvv2 = cvv2;
		this.expriry = expriry;
		this.dateCreate = dateCreate;
		this.dateChange = dateChange;
	}

	@Id
	@Column(name = "id_user", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "payment_type", nullable = false, length = 100)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "payment_email", length = 100)
	public String getPaymentEmail() {
		return this.paymentEmail;
	}

	public void setPaymentEmail(String paymentEmail) {
		this.paymentEmail = paymentEmail;
	}

	@Column(name = "payment_password", length = 100)
	public String getPaymentPassword() {
		return this.paymentPassword;
	}

	public void setPaymentPassword(String paymentPassword) {
		this.paymentPassword = paymentPassword;
	}

	@Column(name = "credit_card_number", length = 100)
	public String getCreditCardNumber() {
		return this.creditCardNumber;
	}

	public void setCreditCardNumber(String creditCardNumber) {
		this.creditCardNumber = creditCardNumber;
	}

	@Column(name = "credit_card_type", length = 100)
	public String getCreditCardType() {
		return this.creditCardType;
	}

	public void setCreditCardType(String creditCardType) {
		this.creditCardType = creditCardType;
	}

	@Column(name = "cvv2", length = 3)
	public String getCvv2() {
		return this.cvv2;
	}

	public void setCvv2(String cvv2) {
		this.cvv2 = cvv2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expriry", length = 10)
	public Date getExpriry() {
		return this.expriry;
	}

	public void setExpriry(Date expriry) {
		this.expriry = expriry;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_change", length = 10)
	public Date getDateChange() {
		return this.dateChange;
	}

	public void setDateChange(Date dateChange) {
		this.dateChange = dateChange;
	}

}
