package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "crevu")
public class Payment implements java.io.Serializable {

	private PaymentId id;

	public Payment() {
	}

	public Payment(PaymentId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idOrderDeal", column = @Column(name = "id_order_deal", nullable = false)),
			@AttributeOverride(name = "paymentType", column = @Column(name = "payment_type", nullable = false, length = 100)),
			@AttributeOverride(name = "paymentEmail", column = @Column(name = "payment_email", length = 100)),
			@AttributeOverride(name = "paymentPassword", column = @Column(name = "payment_password", length = 100)),
			@AttributeOverride(name = "creditCardNumber", column = @Column(name = "credit_card_number", length = 100)),
			@AttributeOverride(name = "creditCardType", column = @Column(name = "credit_card_type", length = 100)),
			@AttributeOverride(name = "cvv2", column = @Column(name = "cvv2", length = 3)),
			@AttributeOverride(name = "expriry", column = @Column(name = "expriry", length = 10)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)) })
	public PaymentId getId() {
		return this.id;
	}

	public void setId(PaymentId id) {
		this.id = id;
	}

}
