package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentId generated by hbm2java
 */
@Embeddable
public class PaymentId implements java.io.Serializable {

	private int idOrderDeal;
	private String paymentType;
	private String paymentEmail;
	private String paymentPassword;
	private String creditCardNumber;
	private String creditCardType;
	private String cvv2;
	private Date expriry;
	private Date dateCreate;

	public PaymentId() {
	}

	public PaymentId(int idOrderDeal, String paymentType) {
		this.idOrderDeal = idOrderDeal;
		this.paymentType = paymentType;
	}

	public PaymentId(int idOrderDeal, String paymentType, String paymentEmail,
			String paymentPassword, String creditCardNumber,
			String creditCardType, String cvv2, Date expriry, Date dateCreate) {
		this.idOrderDeal = idOrderDeal;
		this.paymentType = paymentType;
		this.paymentEmail = paymentEmail;
		this.paymentPassword = paymentPassword;
		this.creditCardNumber = creditCardNumber;
		this.creditCardType = creditCardType;
		this.cvv2 = cvv2;
		this.expriry = expriry;
		this.dateCreate = dateCreate;
	}

	@Column(name = "id_order_deal", nullable = false)
	public int getIdOrderDeal() {
		return this.idOrderDeal;
	}

	public void setIdOrderDeal(int idOrderDeal) {
		this.idOrderDeal = idOrderDeal;
	}

	@Column(name = "payment_type", nullable = false, length = 100)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "payment_email", length = 100)
	public String getPaymentEmail() {
		return this.paymentEmail;
	}

	public void setPaymentEmail(String paymentEmail) {
		this.paymentEmail = paymentEmail;
	}

	@Column(name = "payment_password", length = 100)
	public String getPaymentPassword() {
		return this.paymentPassword;
	}

	public void setPaymentPassword(String paymentPassword) {
		this.paymentPassword = paymentPassword;
	}

	@Column(name = "credit_card_number", length = 100)
	public String getCreditCardNumber() {
		return this.creditCardNumber;
	}

	public void setCreditCardNumber(String creditCardNumber) {
		this.creditCardNumber = creditCardNumber;
	}

	@Column(name = "credit_card_type", length = 100)
	public String getCreditCardType() {
		return this.creditCardType;
	}

	public void setCreditCardType(String creditCardType) {
		this.creditCardType = creditCardType;
	}

	@Column(name = "cvv2", length = 3)
	public String getCvv2() {
		return this.cvv2;
	}

	public void setCvv2(String cvv2) {
		this.cvv2 = cvv2;
	}

	@Column(name = "expriry", length = 10)
	public Date getExpriry() {
		return this.expriry;
	}

	public void setExpriry(Date expriry) {
		this.expriry = expriry;
	}

	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentId))
			return false;
		PaymentId castOther = (PaymentId) other;

		return (this.getIdOrderDeal() == castOther.getIdOrderDeal())
				&& ((this.getPaymentType() == castOther.getPaymentType()) || (this
						.getPaymentType() != null
						&& castOther.getPaymentType() != null && this
						.getPaymentType().equals(castOther.getPaymentType())))
				&& ((this.getPaymentEmail() == castOther.getPaymentEmail()) || (this
						.getPaymentEmail() != null
						&& castOther.getPaymentEmail() != null && this
						.getPaymentEmail().equals(castOther.getPaymentEmail())))
				&& ((this.getPaymentPassword() == castOther
						.getPaymentPassword()) || (this.getPaymentPassword() != null
						&& castOther.getPaymentPassword() != null && this
						.getPaymentPassword().equals(
								castOther.getPaymentPassword())))
				&& ((this.getCreditCardNumber() == castOther
						.getCreditCardNumber()) || (this.getCreditCardNumber() != null
						&& castOther.getCreditCardNumber() != null && this
						.getCreditCardNumber().equals(
								castOther.getCreditCardNumber())))
				&& ((this.getCreditCardType() == castOther.getCreditCardType()) || (this
						.getCreditCardType() != null
						&& castOther.getCreditCardType() != null && this
						.getCreditCardType().equals(
								castOther.getCreditCardType())))
				&& ((this.getCvv2() == castOther.getCvv2()) || (this.getCvv2() != null
						&& castOther.getCvv2() != null && this.getCvv2()
						.equals(castOther.getCvv2())))
				&& ((this.getExpriry() == castOther.getExpriry()) || (this
						.getExpriry() != null && castOther.getExpriry() != null && this
						.getExpriry().equals(castOther.getExpriry())))
				&& ((this.getDateCreate() == castOther.getDateCreate()) || (this
						.getDateCreate() != null
						&& castOther.getDateCreate() != null && this
						.getDateCreate().equals(castOther.getDateCreate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrderDeal();
		result = 37
				* result
				+ (getPaymentType() == null ? 0 : this.getPaymentType()
						.hashCode());
		result = 37
				* result
				+ (getPaymentEmail() == null ? 0 : this.getPaymentEmail()
						.hashCode());
		result = 37
				* result
				+ (getPaymentPassword() == null ? 0 : this.getPaymentPassword()
						.hashCode());
		result = 37
				* result
				+ (getCreditCardNumber() == null ? 0 : this
						.getCreditCardNumber().hashCode());
		result = 37
				* result
				+ (getCreditCardType() == null ? 0 : this.getCreditCardType()
						.hashCode());
		result = 37 * result
				+ (getCvv2() == null ? 0 : this.getCvv2().hashCode());
		result = 37 * result
				+ (getExpriry() == null ? 0 : this.getExpriry().hashCode());
		result = 37
				* result
				+ (getDateCreate() == null ? 0 : this.getDateCreate()
						.hashCode());
		return result;
	}

}
