package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RevenueId generated by hbm2java
 */
@Embeddable
public class RevenueId implements java.io.Serializable {

	private int idUser;
	private int idSoldTshirt;
	private float revenue;
	private float paid;
	private Date dateCreate;

	public RevenueId() {
	}

	public RevenueId(int idUser, int idSoldTshirt, float revenue, float paid) {
		this.idUser = idUser;
		this.idSoldTshirt = idSoldTshirt;
		this.revenue = revenue;
		this.paid = paid;
	}

	public RevenueId(int idUser, int idSoldTshirt, float revenue, float paid,
			Date dateCreate) {
		this.idUser = idUser;
		this.idSoldTshirt = idSoldTshirt;
		this.revenue = revenue;
		this.paid = paid;
		this.dateCreate = dateCreate;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_sold_tshirt", nullable = false)
	public int getIdSoldTshirt() {
		return this.idSoldTshirt;
	}

	public void setIdSoldTshirt(int idSoldTshirt) {
		this.idSoldTshirt = idSoldTshirt;
	}

	@Column(name = "revenue", nullable = false, precision = 12, scale = 0)
	public float getRevenue() {
		return this.revenue;
	}

	public void setRevenue(float revenue) {
		this.revenue = revenue;
	}

	@Column(name = "paid", nullable = false, precision = 12, scale = 0)
	public float getPaid() {
		return this.paid;
	}

	public void setPaid(float paid) {
		this.paid = paid;
	}

	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RevenueId))
			return false;
		RevenueId castOther = (RevenueId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdSoldTshirt() == castOther.getIdSoldTshirt())
				&& (this.getRevenue() == castOther.getRevenue())
				&& (this.getPaid() == castOther.getPaid())
				&& ((this.getDateCreate() == castOther.getDateCreate()) || (this
						.getDateCreate() != null
						&& castOther.getDateCreate() != null && this
						.getDateCreate().equals(castOther.getDateCreate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdSoldTshirt();
		result = 37 * result + (int) this.getRevenue();
		result = 37 * result + (int) this.getPaid();
		result = 37
				* result
				+ (getDateCreate() == null ? 0 : this.getDateCreate()
						.hashCode());
		return result;
	}

}
