package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Revenue generated by hbm2java
 */
@Entity
@Table(name = "revenue", catalog = "crevu")
public class Revenue implements java.io.Serializable {

	private RevenueId id;

	public Revenue() {
	}

	public Revenue(RevenueId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)),
			@AttributeOverride(name = "idSoldTshirt", column = @Column(name = "id_sold_tshirt", nullable = false)),
			@AttributeOverride(name = "revenue", column = @Column(name = "revenue", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "paid", column = @Column(name = "paid", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)) })
	public RevenueId getId() {
		return this.id;
	}

	public void setId(RevenueId id) {
		this.id = id;
	}

}
