package it.crevu.db;

// Generated 1-apr-2013 14.32.17 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserconnectionId generated by hbm2java
 */
@Embeddable
public class SocialUserId implements java.io.Serializable {

	private String userId;
	private String providerId;
	private String providerUserId;

	public SocialUserId() {
	}

	public SocialUserId(String userId, String providerId,
			String providerUserId) {
		this.userId = userId;
		this.providerId = providerId;
		this.providerUserId = providerUserId;
	}

	@Column(name = "userId", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "providerId", nullable = false)
	public String getProviderId() {
		return this.providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	@Column(name = "providerUserId", nullable = false)
	public String getProviderUserId() {
		return this.providerUserId;
	}

	public void setProviderUserId(String providerUserId) {
		this.providerUserId = providerUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SocialUserId))
			return false;
		SocialUserId castOther = (SocialUserId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getProviderId() == castOther.getProviderId()) || (this
						.getProviderId() != null
						&& castOther.getProviderId() != null && this
						.getProviderId().equals(castOther.getProviderId())))
				&& ((this.getProviderUserId() == castOther.getProviderUserId()) || (this
						.getProviderUserId() != null
						&& castOther.getProviderUserId() != null && this
						.getProviderUserId().equals(
								castOther.getProviderUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37
				* result
				+ (getProviderId() == null ? 0 : this.getProviderId()
						.hashCode());
		result = 37
				* result
				+ (getProviderUserId() == null ? 0 : this.getProviderUserId()
						.hashCode());
		return result;
	}

}
