package it.crevu.db;

// Generated 20-apr-2013 15.10.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SocialAccount generated by hbm2java
 */
@Entity
@Table(name = "social_account", catalog = "crevu")
public class SocialAccount implements java.io.Serializable {

	private Integer id;
	private int idUser;
	private String accountType;
	private String socialId;
	private String socialPassword;
	private Date dateCreate;
	private Date dateChange;
	private String accessTokenValue;
	private String accessTokenSecret;

	public SocialAccount() {
	}

	public SocialAccount(int idUser, String accountType) {
		this.idUser = idUser;
		this.accountType = accountType;
	}

	public SocialAccount(int idUser, String accountType, String socialId,
			String socialPassword, Date dateCreate, Date dateChange,
			String accessTokenValue, String accessTokenSecret) {
		this.idUser = idUser;
		this.accountType = accountType;
		this.socialId = socialId;
		this.socialPassword = socialPassword;
		this.dateCreate = dateCreate;
		this.dateChange = dateChange;
		this.accessTokenValue = accessTokenValue;
		this.accessTokenSecret = accessTokenSecret;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "account_type", nullable = false, length = 50)
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "social_id", length = 100)
	public String getSocialId() {
		return this.socialId;
	}

	public void setSocialId(String socialId) {
		this.socialId = socialId;
	}

	@Column(name = "social_password", length = 100)
	public String getSocialPassword() {
		return this.socialPassword;
	}

	public void setSocialPassword(String socialPassword) {
		this.socialPassword = socialPassword;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_change", length = 10)
	public Date getDateChange() {
		return this.dateChange;
	}

	public void setDateChange(Date dateChange) {
		this.dateChange = dateChange;
	}

	@Column(name = "access_token_value", length = 500)
	public String getAccessTokenValue() {
		return this.accessTokenValue;
	}

	public void setAccessTokenValue(String accessTokenValue) {
		this.accessTokenValue = accessTokenValue;
	}

	@Column(name = "access_token_secret", length = 500)
	public String getAccessTokenSecret() {
		return this.accessTokenSecret;
	}

	public void setAccessTokenSecret(String accessTokenSecret) {
		this.accessTokenSecret = accessTokenSecret;
	}

}
