package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SoldTshirtId generated by hbm2java
 */
@Embeddable
public class SoldTshirtId implements java.io.Serializable {

	private int id;
	private int idBuyer;
	private int idSeller;
	private int idTshirtProposal;
	private Date dateCreate;

	public SoldTshirtId() {
	}

	public SoldTshirtId(int id, int idBuyer, int idSeller, int idTshirtProposal) {
		this.id = id;
		this.idBuyer = idBuyer;
		this.idSeller = idSeller;
		this.idTshirtProposal = idTshirtProposal;
	}

	public SoldTshirtId(int id, int idBuyer, int idSeller,
			int idTshirtProposal, Date dateCreate) {
		this.id = id;
		this.idBuyer = idBuyer;
		this.idSeller = idSeller;
		this.idTshirtProposal = idTshirtProposal;
		this.dateCreate = dateCreate;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "id_buyer", nullable = false)
	public int getIdBuyer() {
		return this.idBuyer;
	}

	public void setIdBuyer(int idBuyer) {
		this.idBuyer = idBuyer;
	}

	@Column(name = "id_seller", nullable = false)
	public int getIdSeller() {
		return this.idSeller;
	}

	public void setIdSeller(int idSeller) {
		this.idSeller = idSeller;
	}

	@Column(name = "id_tshirt_proposal", nullable = false)
	public int getIdTshirtProposal() {
		return this.idTshirtProposal;
	}

	public void setIdTshirtProposal(int idTshirtProposal) {
		this.idTshirtProposal = idTshirtProposal;
	}

	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SoldTshirtId))
			return false;
		SoldTshirtId castOther = (SoldTshirtId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdBuyer() == castOther.getIdBuyer())
				&& (this.getIdSeller() == castOther.getIdSeller())
				&& (this.getIdTshirtProposal() == castOther
						.getIdTshirtProposal())
				&& ((this.getDateCreate() == castOther.getDateCreate()) || (this
						.getDateCreate() != null
						&& castOther.getDateCreate() != null && this
						.getDateCreate().equals(castOther.getDateCreate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdBuyer();
		result = 37 * result + this.getIdSeller();
		result = 37 * result + this.getIdTshirtProposal();
		result = 37
				* result
				+ (getDateCreate() == null ? 0 : this.getDateCreate()
						.hashCode());
		return result;
	}

}
