package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SupplierOrder generated by hbm2java
 */
@Entity
@Table(name = "supplier_order", catalog = "crevu", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id", "date_create" }))
public class SupplierOrder implements java.io.Serializable {

	private SupplierOrderId id;

	public SupplierOrder() {
	}

	public SupplierOrder(SupplierOrderId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "idOrderDeal", column = @Column(name = "id_order_deal", nullable = false)),
			@AttributeOverride(name = "idWarehouse", column = @Column(name = "id_warehouse", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 1)),
			@AttributeOverride(name = "tshirtNumber", column = @Column(name = "tshirt_number", nullable = false)),
			@AttributeOverride(name = "attachmentName", column = @Column(name = "attachment_name", nullable = false, length = 100)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)),
			@AttributeOverride(name = "dateChange", column = @Column(name = "date_change", length = 10)) })
	public SupplierOrderId getId() {
		return this.id;
	}

	public void setId(SupplierOrderId id) {
		this.id = id;
	}

}
