package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Text generated by hbm2java
 */
@Entity
@Table(name = "text", catalog = "crevu", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "id", "date_create" }),
		@UniqueConstraint(columnNames = "body") })
public class Text implements java.io.Serializable {

	private TextId id;

	public Text() {
	}

	public Text(TextId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "body", column = @Column(name = "body", unique = true, nullable = false, length = 100)),
			@AttributeOverride(name = "source", column = @Column(name = "source", nullable = false, length = 100)),
			@AttributeOverride(name = "votes", column = @Column(name = "votes")),
			@AttributeOverride(name = "bad", column = @Column(name = "bad", nullable = false)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)),
			@AttributeOverride(name = "dateChange", column = @Column(name = "date_change", length = 10)) })
	public TextId getId() {
		return this.id;
	}

	public void setId(TextId id) {
		this.id = id;
	}

}
