package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TextId generated by hbm2java
 */
@Embeddable
public class TextId implements java.io.Serializable {

	private int id;
	private String body;
	private String source;
	private Integer votes;
	private boolean bad;
	private Date dateCreate;
	private Date dateChange;

	public TextId() {
	}

	public TextId(int id, String body, String source, boolean bad) {
		this.id = id;
		this.body = body;
		this.source = source;
		this.bad = bad;
	}

	public TextId(int id, String body, String source, Integer votes,
			boolean bad, Date dateCreate, Date dateChange) {
		this.id = id;
		this.body = body;
		this.source = source;
		this.votes = votes;
		this.bad = bad;
		this.dateCreate = dateCreate;
		this.dateChange = dateChange;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "body", unique = true, nullable = false, length = 100)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "source", nullable = false, length = 100)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "votes")
	public Integer getVotes() {
		return this.votes;
	}

	public void setVotes(Integer votes) {
		this.votes = votes;
	}

	@Column(name = "bad", nullable = false)
	public boolean isBad() {
		return this.bad;
	}

	public void setBad(boolean bad) {
		this.bad = bad;
	}

	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "date_change", length = 10)
	public Date getDateChange() {
		return this.dateChange;
	}

	public void setDateChange(Date dateChange) {
		this.dateChange = dateChange;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TextId))
			return false;
		TextId castOther = (TextId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getBody() == castOther.getBody()) || (this.getBody() != null
						&& castOther.getBody() != null && this.getBody()
						.equals(castOther.getBody())))
				&& ((this.getSource() == castOther.getSource()) || (this
						.getSource() != null && castOther.getSource() != null && this
						.getSource().equals(castOther.getSource())))
				&& ((this.getVotes() == castOther.getVotes()) || (this
						.getVotes() != null && castOther.getVotes() != null && this
						.getVotes().equals(castOther.getVotes())))
				&& (this.isBad() == castOther.isBad())
				&& ((this.getDateCreate() == castOther.getDateCreate()) || (this
						.getDateCreate() != null
						&& castOther.getDateCreate() != null && this
						.getDateCreate().equals(castOther.getDateCreate())))
				&& ((this.getDateChange() == castOther.getDateChange()) || (this
						.getDateChange() != null
						&& castOther.getDateChange() != null && this
						.getDateChange().equals(castOther.getDateChange())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getBody() == null ? 0 : this.getBody().hashCode());
		result = 37 * result
				+ (getSource() == null ? 0 : this.getSource().hashCode());
		result = 37 * result
				+ (getVotes() == null ? 0 : this.getVotes().hashCode());
		result = 37 * result + (this.isBad() ? 1 : 0);
		result = 37
				* result
				+ (getDateCreate() == null ? 0 : this.getDateCreate()
						.hashCode());
		result = 37
				* result
				+ (getDateChange() == null ? 0 : this.getDateChange()
						.hashCode());
		return result;
	}

}
