package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionId generated by hbm2java
 */
@Embeddable
public class TransactionId implements java.io.Serializable {

	private int id;
	private int idWarehouse;
	private int idSupplierOrder;
	private float amount;
	private char status;
	private Date dateCreate;
	private Date dateChange;

	public TransactionId() {
	}

	public TransactionId(int id, int idWarehouse, int idSupplierOrder,
			float amount, char status) {
		this.id = id;
		this.idWarehouse = idWarehouse;
		this.idSupplierOrder = idSupplierOrder;
		this.amount = amount;
		this.status = status;
	}

	public TransactionId(int id, int idWarehouse, int idSupplierOrder,
			float amount, char status, Date dateCreate, Date dateChange) {
		this.id = id;
		this.idWarehouse = idWarehouse;
		this.idSupplierOrder = idSupplierOrder;
		this.amount = amount;
		this.status = status;
		this.dateCreate = dateCreate;
		this.dateChange = dateChange;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "id_warehouse", nullable = false)
	public int getIdWarehouse() {
		return this.idWarehouse;
	}

	public void setIdWarehouse(int idWarehouse) {
		this.idWarehouse = idWarehouse;
	}

	@Column(name = "id_supplier_order", nullable = false)
	public int getIdSupplierOrder() {
		return this.idSupplierOrder;
	}

	public void setIdSupplierOrder(int idSupplierOrder) {
		this.idSupplierOrder = idSupplierOrder;
	}

	@Column(name = "amount", nullable = false, precision = 12, scale = 0)
	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "date_create", length = 10)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "date_change", length = 10)
	public Date getDateChange() {
		return this.dateChange;
	}

	public void setDateChange(Date dateChange) {
		this.dateChange = dateChange;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionId))
			return false;
		TransactionId castOther = (TransactionId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdWarehouse() == castOther.getIdWarehouse())
				&& (this.getIdSupplierOrder() == castOther.getIdSupplierOrder())
				&& (this.getAmount() == castOther.getAmount())
				&& (this.getStatus() == castOther.getStatus())
				&& ((this.getDateCreate() == castOther.getDateCreate()) || (this
						.getDateCreate() != null
						&& castOther.getDateCreate() != null && this
						.getDateCreate().equals(castOther.getDateCreate())))
				&& ((this.getDateChange() == castOther.getDateChange()) || (this
						.getDateChange() != null
						&& castOther.getDateChange() != null && this
						.getDateChange().equals(castOther.getDateChange())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdWarehouse();
		result = 37 * result + this.getIdSupplierOrder();
		result = 37 * result + (int) this.getAmount();
		result = 37 * result + this.getStatus();
		result = 37
				* result
				+ (getDateCreate() == null ? 0 : this.getDateCreate()
						.hashCode());
		result = 37
				* result
				+ (getDateChange() == null ? 0 : this.getDateChange()
						.hashCode());
		return result;
	}

}
