package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", catalog = "crevu", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id", "date_create" }))
public class Transaction implements java.io.Serializable {

	private TransactionId id;

	public Transaction() {
	}

	public Transaction(TransactionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "idWarehouse", column = @Column(name = "id_warehouse", nullable = false)),
			@AttributeOverride(name = "idSupplierOrder", column = @Column(name = "id_supplier_order", nullable = false)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 1)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)),
			@AttributeOverride(name = "dateChange", column = @Column(name = "date_change", length = 10)) })
	public TransactionId getId() {
		return this.id;
	}

	public void setId(TransactionId id) {
		this.id = id;
	}

}
