package it.crevu.db;

// Generated 26-mar-2013 21.12.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TshirtCategory generated by hbm2java
 */
@Entity
@Table(name = "tshirt_category", catalog = "crevu")
public class TshirtCategory implements java.io.Serializable {

	private TshirtCategoryId id;
	private int idCategory;
	private int idTshirtProposal;

	public TshirtCategory() {
	}

	public TshirtCategory(TshirtCategoryId id, int idCategory,
			int idTshirtProposal) {
		this.id = id;
		this.idCategory = idCategory;
		this.idTshirtProposal = idTshirtProposal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", nullable = false, length = 10)) })
	public TshirtCategoryId getId() {
		return this.id;
	}

	public void setId(TshirtCategoryId id) {
		this.id = id;
	}

	@Column(name = "id_category", nullable = false)
	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "id_tshirt_proposal", nullable = false)
	public int getIdTshirtProposal() {
		return this.idTshirtProposal;
	}

	public void setIdTshirtProposal(int idTshirtProposal) {
		this.idTshirtProposal = idTshirtProposal;
	}

}
