package it.crevu.db;

// Generated 20-apr-2013 15.10.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TshirtProposal generated by hbm2java
 */
@Entity
@Table(name = "tshirt_proposal", catalog = "crevu", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id", "date_create" }))
public class TshirtProposal implements java.io.Serializable {

	private TshirtProposalId id;

	public TshirtProposal() {
	}

	public TshirtProposal(TshirtProposalId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)),
			@AttributeOverride(name = "idText", column = @Column(name = "id_text", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 100)),
			@AttributeOverride(name = "color", column = @Column(name = "color", length = 100)),
			@AttributeOverride(name = "price", column = @Column(name = "price", precision = 12, scale = 0)),
			@AttributeOverride(name = "approved", column = @Column(name = "approved", nullable = false)),
			@AttributeOverride(name = "votes", column = @Column(name = "votes", nullable = false)),
			@AttributeOverride(name = "likes", column = @Column(name = "likes", nullable = false)),
			@AttributeOverride(name = "retweets", column = @Column(name = "retweets", nullable = false)),
			@AttributeOverride(name = "brand", column = @Column(name = "brand", length = 100)),
			@AttributeOverride(name = "active", column = @Column(name = "active", nullable = false)),
			@AttributeOverride(name = "dateCreate", column = @Column(name = "date_create", length = 10)),
			@AttributeOverride(name = "dateChange", column = @Column(name = "date_change", length = 10)),
			@AttributeOverride(name = "personalRank", column = @Column(name = "personal_rank")) })
	public TshirtProposalId getId() {
		return this.id;
	}

	public void setId(TshirtProposalId id) {
		this.id = id;
	}

}
