package it.crevu.db;

// Generated 20-apr-2013 15.10.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserCommunication generated by hbm2java
 */
@Entity
@Table(name = "user_communication", catalog = "crevu")
public class UserCommunication implements java.io.Serializable {

	private Integer id;
	private int idUser;
	private String message;
	private Date dateRanking;

	public UserCommunication() {
	}

	public UserCommunication(int idUser) {
		this.idUser = idUser;
	}

	public UserCommunication(int idUser, String message, Date dateRanking) {
		this.idUser = idUser;
		this.message = message;
		this.dateRanking = dateRanking;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "message", length = 4000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ranking", length = 10)
	public Date getDateRanking() {
		return this.dateRanking;
	}

	public void setDateRanking(Date dateRanking) {
		this.dateRanking = dateRanking;
	}

}
