package it.crevu.db;

// Generated 20-apr-2013 15.10.16 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserTshirtRanking generated by hbm2java
 */
@Entity
@Table(name = "user_tshirt_ranking", catalog = "crevu")
public class UserTshirtRanking implements java.io.Serializable {

	private UserTshirtRankingId id;

	public UserTshirtRanking() {
	}

	public UserTshirtRanking(UserTshirtRankingId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)),
			@AttributeOverride(name = "idTshirt", column = @Column(name = "id_tshirt", nullable = false)),
			@AttributeOverride(name = "position", column = @Column(name = "position", nullable = false)),
			@AttributeOverride(name = "dateRanking", column = @Column(name = "date_ranking", length = 10)) })
	public UserTshirtRankingId getId() {
		return this.id;
	}

	public void setId(UserTshirtRankingId id) {
		this.id = id;
	}

}
