package it.crevu.db;

// Generated 20-apr-2013 15.10.16 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserTshirtRankingId generated by hbm2java
 */
@Embeddable
public class UserTshirtRankingId implements java.io.Serializable {

	private int idUser;
	private int idTshirt;
	private int position;
	private Date dateRanking;

	public UserTshirtRankingId() {
	}

	public UserTshirtRankingId(int idUser, int idTshirt, int position) {
		this.idUser = idUser;
		this.idTshirt = idTshirt;
		this.position = position;
	}

	public UserTshirtRankingId(int idUser, int idTshirt, int position,
			Date dateRanking) {
		this.idUser = idUser;
		this.idTshirt = idTshirt;
		this.position = position;
		this.dateRanking = dateRanking;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_tshirt", nullable = false)
	public int getIdTshirt() {
		return this.idTshirt;
	}

	public void setIdTshirt(int idTshirt) {
		this.idTshirt = idTshirt;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "date_ranking", length = 10)
	public Date getDateRanking() {
		return this.dateRanking;
	}

	public void setDateRanking(Date dateRanking) {
		this.dateRanking = dateRanking;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserTshirtRankingId))
			return false;
		UserTshirtRankingId castOther = (UserTshirtRankingId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdTshirt() == castOther.getIdTshirt())
				&& (this.getPosition() == castOther.getPosition())
				&& ((this.getDateRanking() == castOther.getDateRanking()) || (this
						.getDateRanking() != null
						&& castOther.getDateRanking() != null && this
						.getDateRanking().equals(castOther.getDateRanking())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdTshirt();
		result = 37 * result + this.getPosition();
		result = 37
				* result
				+ (getDateRanking() == null ? 0 : this.getDateRanking()
						.hashCode());
		return result;
	}

}
